

[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
kbuild = "build --target x86_64-quantum_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-quantum_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-quantum_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --target x86_64-quantum_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]