[package]
name = "quantum_os"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "boot",
]

[dependencies]
bootloader = "0.10.12"
no-std-compat = "0.4.1"
volatile = "0.2.6"
spin = "0.5.2"

# Please Remove
uart_16550 = "0.2.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

