[package]
name = "quantum_os"
version = "0.1.0"
edition = "2021"
build="build.rs"

[workspace]
members = [
    "boot",
    "quantum_boot/src/bios_boot/bios",
    "quantum_boot/src/bios_boot/stage-1",
    "quantum_boot/src/bios_boot/stage-2",
]

[features]
default = [ "nightly", "instructions" ]
nightly = [ "const_fn", "abi_x86_interrupt" ]
abi_x86_interrupt = []
instructions = []
const_fn = []

[profile.dev]
panic = "unwind"

[dependencies]
bootloader = "0.10.12"
no-std-compat = "0.4.1"
volatile = "0.4.5"
spin = "0.9.4"

# Should be implmented in Quantum down the line
x86_64 = "0.14.9"
owo-colors = "3.4.0"
heapless = "0.7.16"

[package.metadata.bootloader]
kernel-stack-size = 204800

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
