[package]
name = "stage-1"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[profile.release]
opt-level = "z"
#lto = true
#codegen-units = 1
debug = false
overflow-checks = false


[build-dependencies]
nasm-rs = "0.2.4"