
[alias]
kbuild = "build --target ../i686-quantum_loader.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]